name: flutter_state_migrator
description: "Automated CLI tool to migrate Flutter apps from Provider, BLoC, GetX, and MobX to Riverpod."
version: 2.5.0
homepage: https://github.com/RanveerSingh1997/flutter-state-migrator
repository: https://github.com/RanveerSingh1997/flutter-state-migrator

executables:
  migrator: migrator

environment:
  sdk: ^3.9.2

dependencies:
  analyzer: ^13.0.0
  args: ^2.7.0
  path: ^1.9.1
  yaml: ^3.1.3
  http: ^1.6.0

dev_dependencies:
  test: ^1.24.0
  lints: ^6.1.0
