/// Manages `import` statements in migrated Dart files.
///
/// Adds `flutter_riverpod` when Riverpod consumer symbols are present,
/// adds `riverpod_annotation` when `@riverpod` annotations or `.g.dart` part
/// directives are present, and optionally removes the legacy `provider` import
/// when it is no longer needed.
class ImportManager {
  static const _flutterRiverpodImport =
      "import 'package:flutter_riverpod/flutter_riverpod.dart';";
  static const _riverpodAnnotationImport =
      "import 'package:riverpod_annotation/riverpod_annotation.dart';";

  /// Injects required Riverpod imports and optionally removes the legacy
  /// Provider import.
  ///
  /// - [cleanProvider]: when true, removes the `provider` package import if no
  ///   Provider-framework symbols remain in the post-migration content.
  String processImports(String content, {bool cleanProvider = true}) {
    String out = content;

    // Strip comments from a working copy used only for symbol detection,
    // so that `// ConsumerWidget` in a comment never triggers import injection.
    final stripped = _stripComments(out);

    // ── 1. riverpod_annotation ──────────────────────────────────────────────
    // Needed whenever the file contains @riverpod annotations or a .g.dart
    // part directive (both are generated by riverpod_transformer).
    final needsAnnotation =
        RegExp(r'@riverpod\b').hasMatch(stripped) ||
        RegExp(r"part\s+'[^']+\.g\.dart'\s*;").hasMatch(stripped);

    final hasAnnotationImport = out.contains(
      "import 'package:riverpod_annotation/riverpod_annotation.dart'",
    );

    if (needsAnnotation && !hasAnnotationImport) {
      out = _insertImport(out, _riverpodAnnotationImport);
    }

    // ── 2. flutter_riverpod ─────────────────────────────────────────────────
    // Needed whenever consumer-side Riverpod symbols appear in the file.
    final needsFlutterRiverpod =
        RegExp(r'\bConsumerWidget\b').hasMatch(stripped) ||
        RegExp(r'\bConsumerState\b').hasMatch(stripped) ||
        RegExp(r'\bConsumerStatefulWidget\b').hasMatch(stripped) ||
        RegExp(r'\bHookConsumerWidget\b').hasMatch(stripped) ||
        RegExp(r'\bProviderScope\b').hasMatch(stripped) ||
        RegExp(r'\bref\.(?:watch|read|listen)\b').hasMatch(stripped) ||
        RegExp(r'\bWidgetRef\b').hasMatch(stripped);

    final hasFlutterRiverpodImport = out.contains(
      "import 'package:flutter_riverpod/flutter_riverpod.dart'",
    );

    if (needsFlutterRiverpod && !hasFlutterRiverpodImport) {
      out = _insertImport(out, _flutterRiverpodImport);
    }

    // ── 3. Remove legacy Provider import when no longer used ────────────────
    if (cleanProvider && _isProviderImportPresent(out)) {
      if (!_isProviderStillUsed(out)) {
        out = out.replaceAll(
          RegExp(r"import\s+'package:provider/provider\.dart'\s*;\n?"),
          '',
        );
      }
    }

    return out;
  }

  // ── helpers ─────────────────────────────────────────────────────────────

  /// Returns a copy of [content] with single-line and multi-line comments
  /// removed — used only for symbol detection to avoid false positives.
  String _stripComments(String content) {
    // Remove multi-line comments first.
    var result = content.replaceAll(
      RegExp(r'/\*.*?\*/', dotAll: true),
      '',
    );
    // Remove single-line comments.
    result = result.replaceAll(RegExp(r'//[^\n]*'), '');
    return result;
  }

  /// Inserts [importLine] after the last `import` statement in [content], or
  /// prepends it when no imports exist yet.
  String _insertImport(String content, String importLine) {
    final lastImportMatch = RegExp(
      r'^import\s+.*;$',
      multiLine: true,
    ).allMatches(content).lastOrNull;

    if (lastImportMatch != null) {
      final insertAt = lastImportMatch.end;
      return content.replaceRange(insertAt, insertAt, '\n$importLine');
    }
    return '$importLine\n$content';
  }

  bool _isProviderImportPresent(String content) =>
      content.contains("import 'package:provider/provider.dart'");

  /// Returns true when Provider-framework symbols appear outside of import
  /// lines and comment lines — i.e. the provider package is still required.
  bool _isProviderStillUsed(String content) {
    final usagePattern = RegExp(
      r'\b(?:ChangeNotifier|ChangeNotifierProvider|Consumer|MultiProvider|Selector|Provider)\b',
    );
    for (final match in usagePattern.allMatches(content)) {
      final lineStart = content.lastIndexOf('\n', match.start) + 1;
      final lineEnd = content.indexOf('\n', match.start);
      final line = content.substring(
        lineStart,
        lineEnd != -1 ? lineEnd : content.length,
      );
      final trimmed = line.trim();
      if (!trimmed.startsWith('import') && !trimmed.startsWith('//')) {
        return true;
      }
    }
    return false;
  }
}
